---
- name: Configure bluetooth headset
  hosts: localhost
  gather_facts: no
  collections: 
    - ansible.builtin
    - community.general
  tasks:
    - name: Ensure bluetooth is not blocked by rfkill
      block: 
        - name: Register rfkill bluetooth info
          shell: rfkill -J | jq '.[""][] | select(.type == "bluetooth")'
          register: rfkill_bluetooth_command
          changed_when: false

        - name: Get soft-blocked status
          set_fact: 
            soft_status: "{{ rfkill_bluetooth_command.stdout | from_json | json_query('soft') }}" 

        - name: Get hard-blocked status
          debug:
            msg: "{{ rfkill_bluetooth_command.stdout | from_json | json_query('hard') }}" 
          register: hard_status

        - name: Unblock bluetooth
          when: soft_status == 'blocked'
          become: yes
          command: rfkill unblock bluetooth
